"""
ToolSynthesizer — creates new Python tool modules on the fly.

When the autonomous loop diagnoses that a required capability is missing,
this synthesizer:
1. Analyses what kind of tool is needed (from error + context)
2. Picks a template (executor, analyzer, generator, data-pipeline)
3. Generates a concrete module with the right signature
4. Writes it to src/tools/synthesized/generated/<name>.py
5. Registers it in the runtime registry so the immediate retry can use it
6. Records the synthesis event in the failure-memory DB

The generated code is deterministic (no exec/eval of user input).
Templates are filled with validated, sanitised parameters only.
"""

import importlib
import json
import logging
import re
import sqlite3
import textwrap
from datetime import datetime
from hashlib import sha256
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GENERATED_DIR = Path(__file__).resolve().parent / "generated"
REGISTRY_DB = Path(__file__).resolve().parent.parent.parent.parent / "data" / "synthesized_tools.db"

# Safe characters for tool names (prevents path traversal / injection)
SAFE_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,60}$")

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

# Each template is a complete Python module string with {placeholders}.
# The synthesizer fills in: tool_name, description, input_fields, logic_body.

TEMPLATES: Dict[str, str] = {
    # --- Executor: runs a shell command or subprocess ---
    "executor": textwrap.dedent('''\
        """
        Synthesized tool: {tool_name}
        
        {description}
        
        Auto-generated by Phase 51 ToolSynthesizer on {timestamp}.
        """
        
        import logging
        import subprocess
        from typing import Any, Dict
        
        logger = logging.getLogger(__name__)
        
        TOOL_SPEC = {{
            "name": "{tool_name}",
            "description": "{description}",
            "category": "executor",
            "func_name": "run",
            "input_fields": {input_fields},
            "synthesized": True,
            "created": "{timestamp}",
        }}
        
        
        def run({params_signature}) -> Dict[str, Any]:
            """Execute the tool and return a result dict."""
            logger.info(f"[{{TOOL_SPEC['name']}}] Starting execution")
            try:
        {logic_body}
                return {{"status": "success", "output": result}}
            except Exception as e:
                logger.error(f"[{{TOOL_SPEC['name']}}] Failed: {{e}}")
                return {{"status": "failed", "error": str(e)}}
    '''),

    # --- Analyzer: reads data, returns analysis dict ---
    "analyzer": textwrap.dedent('''\
        """
        Synthesized tool: {tool_name}
        
        {description}
        
        Auto-generated by Phase 51 ToolSynthesizer on {timestamp}.
        """
        
        import logging
        from pathlib import Path
        from typing import Any, Dict, List
        
        logger = logging.getLogger(__name__)
        
        TOOL_SPEC = {{
            "name": "{tool_name}",
            "description": "{description}",
            "category": "analyzer",
            "func_name": "run",
            "input_fields": {input_fields},
            "synthesized": True,
            "created": "{timestamp}",
        }}
        
        
        def run({params_signature}) -> Dict[str, Any]:
            """Analyze input and return structured results."""
            logger.info(f"[{{TOOL_SPEC['name']}}] Running analysis")
            try:
        {logic_body}
                return {{"status": "success", "analysis": result}}
            except Exception as e:
                logger.error(f"[{{TOOL_SPEC['name']}}] Failed: {{e}}")
                return {{"status": "failed", "error": str(e)}}
    '''),

    # --- Generator: produces code or files ---
    "generator": textwrap.dedent('''\
        """
        Synthesized tool: {tool_name}
        
        {description}
        
        Auto-generated by Phase 51 ToolSynthesizer on {timestamp}.
        """
        
        import logging
        from pathlib import Path
        from typing import Any, Dict
        
        logger = logging.getLogger(__name__)
        
        TOOL_SPEC = {{
            "name": "{tool_name}",
            "description": "{description}",
            "category": "generator",
            "func_name": "run",
            "input_fields": {input_fields},
            "synthesized": True,
            "created": "{timestamp}",
        }}
        
        
        def run({params_signature}) -> Dict[str, Any]:
            """Generate output and return result."""
            logger.info(f"[{{TOOL_SPEC['name']}}] Generating output")
            try:
        {logic_body}
                return {{"status": "success", "generated": result}}
            except Exception as e:
                logger.error(f"[{{TOOL_SPEC['name']}}] Failed: {{e}}")
                return {{"status": "failed", "error": str(e)}}
    '''),

    # --- Data pipeline: read -> transform -> write ---
    "data_pipeline": textwrap.dedent('''\
        """
        Synthesized tool: {tool_name}
        
        {description}
        
        Auto-generated by Phase 51 ToolSynthesizer on {timestamp}.
        """
        
        import json
        import logging
        from pathlib import Path
        from typing import Any, Dict, List
        
        logger = logging.getLogger(__name__)
        
        TOOL_SPEC = {{
            "name": "{tool_name}",
            "description": "{description}",
            "category": "data_pipeline",
            "func_name": "run",
            "input_fields": {input_fields},
            "synthesized": True,
            "created": "{timestamp}",
        }}
        
        
        def run({params_signature}) -> Dict[str, Any]:
            """Process data pipeline and return results."""
            logger.info(f"[{{TOOL_SPEC['name']}}] Running data pipeline")
            try:
        {logic_body}
                return {{"status": "success", "records_processed": len(result), "output": result}}
            except Exception as e:
                logger.error(f"[{{TOOL_SPEC['name']}}] Failed: {{e}}")
                return {{"status": "failed", "error": str(e)}}
    '''),
}


# ---------------------------------------------------------------------------
# Logic snippets — safe code blocks that the synthesizer can slot in
# ---------------------------------------------------------------------------

LOGIC_SNIPPETS: Dict[str, str] = {
    # File reading
    "read_file": textwrap.dedent("""\
                file_path = Path(source_path)
                if not file_path.exists():
                    return {"status": "failed", "error": f"File not found: {source_path}"}
                content = file_path.read_text(encoding="utf-8")
                result = {"path": str(file_path), "size": len(content), "content": content}"""),

    # File writing
    "write_file": textwrap.dedent("""\
                target = Path(target_path)
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
                result = {"path": str(target), "bytes_written": len(content)}"""),

    # JSON transform
    "json_transform": textwrap.dedent("""\
                import json as _json
                data = _json.loads(input_data) if isinstance(input_data, str) else input_data
                result = {k: v for k, v in data.items() if v is not None}"""),

    # Directory listing
    "list_directory": textwrap.dedent("""\
                dir_path = Path(directory)
                if not dir_path.is_dir():
                    return {"status": "failed", "error": f"Not a directory: {directory}"}
                entries = sorted(str(p.relative_to(dir_path)) for p in dir_path.iterdir())
                result = {"directory": str(dir_path), "entries": entries, "count": len(entries)}"""),

    # Text search
    "text_search": textwrap.dedent("""\
                import re as _re
                matches = []
                pattern = _re.compile(pattern_str, _re.IGNORECASE)
                for line_num, line in enumerate(text.splitlines(), 1):
                    if pattern.search(line):
                        matches.append({"line": line_num, "text": line.strip()})
                result = {"pattern": pattern_str, "match_count": len(matches), "matches": matches[:100]}"""),

    # HTTP fetch (safe — only GET, no auth forwarding)
    "http_fetch": textwrap.dedent("""\
                import urllib.request
                req = urllib.request.Request(url, method="GET")
                with urllib.request.urlopen(req, timeout=30) as resp:
                    body = resp.read().decode("utf-8", errors="replace")
                result = {"url": url, "status": resp.status, "length": len(body), "body": body[:10000]}"""),

    # Subprocess (sandboxed — no shell=True)
    "run_command": textwrap.dedent("""\
                import subprocess as _sp
                proc = _sp.run(
                    command if isinstance(command, list) else command.split(),
                    capture_output=True, text=True, timeout=60, shell=False,
                )
                result = {"returncode": proc.returncode, "stdout": proc.stdout[:5000], "stderr": proc.stderr[:2000]}"""),

    # Placeholder / generic
    "passthrough": textwrap.dedent("""\
                result = {"input": str(input_data)[:1000], "note": "Passthrough — replace with real logic"}"""),
}


# ---------------------------------------------------------------------------
# ToolSynthesizer
# ---------------------------------------------------------------------------

class ToolSynthesizer:
    """
    Creates new tool modules on-the-fly when the autonomous loop determines
    a needed capability is missing.

    Workflow:
        1. diagnose_missing_tool(error, context)  → ToolSpec dict
        2. synthesize(spec)                        → writes .py, registers, returns path
        3. The autonomous loop retries with the new tool available
    """

    def __init__(self):
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        REGISTRY_DB.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    # ------------------------------------------------------------------
    # Persistence — SQLite registry of all synthesized tools
    # ------------------------------------------------------------------

    def _init_db(self):
        conn = sqlite3.connect(str(REGISTRY_DB))
        conn.execute("""
            CREATE TABLE IF NOT EXISTS synthesized_tools (
                tool_name    TEXT PRIMARY KEY,
                category     TEXT NOT NULL,
                description  TEXT,
                file_path    TEXT NOT NULL,
                logic_key    TEXT,
                input_fields TEXT,
                created_at   TEXT NOT NULL,
                triggered_by TEXT,
                times_used   INTEGER DEFAULT 0,
                times_succeeded INTEGER DEFAULT 0
            )
        """)
        conn.commit()
        conn.close()

    def _record_tool(self, spec: Dict) -> None:
        conn = sqlite3.connect(str(REGISTRY_DB))
        conn.execute(
            """INSERT OR REPLACE INTO synthesized_tools
               (tool_name, category, description, file_path, logic_key, input_fields, created_at, triggered_by)
               VALUES (?,?,?,?,?,?,?,?)""",
            (
                spec["tool_name"],
                spec["category"],
                spec.get("description", ""),
                spec.get("file_path", ""),
                spec.get("logic_key", ""),
                json.dumps(spec.get("input_fields", [])),
                datetime.utcnow().isoformat(),
                spec.get("triggered_by", ""),
            ),
        )
        conn.commit()
        conn.close()

    def record_usage(self, tool_name: str, succeeded: bool) -> None:
        """Increment usage counters for a synthesized tool."""
        conn = sqlite3.connect(str(REGISTRY_DB))
        if succeeded:
            conn.execute(
                "UPDATE synthesized_tools SET times_used = times_used + 1, times_succeeded = times_succeeded + 1 WHERE tool_name = ?",
                (tool_name,),
            )
        else:
            conn.execute(
                "UPDATE synthesized_tools SET times_used = times_used + 1 WHERE tool_name = ?",
                (tool_name,),
            )
        conn.commit()
        conn.close()

    def list_synthesized_tools(self) -> List[Dict]:
        """Return all synthesized tools from the DB."""
        conn = sqlite3.connect(str(REGISTRY_DB))
        cur = conn.execute("SELECT tool_name, category, description, times_used, times_succeeded, created_at FROM synthesized_tools ORDER BY created_at DESC")
        rows = [
            {"tool_name": r[0], "category": r[1], "description": r[2],
             "times_used": r[3], "times_succeeded": r[4], "created_at": r[5]}
            for r in cur.fetchall()
        ]
        conn.close()
        return rows

    # ------------------------------------------------------------------
    # Diagnosis — figure out WHAT tool is needed from the error
    # ------------------------------------------------------------------

    def diagnose_missing_tool(
        self, error: str, task: str, context: Dict[str, Any]
    ) -> Optional[Dict]:
        """
        Analyse an error + context to determine if a missing tool caused it,
        and if so, return a spec describing the tool that should be created.

        Returns None if the error is not a missing-tool problem.
        Returns a dict with keys: tool_name, category, description,
               input_fields, logic_key, params_signature, triggered_by
        """
        error_lower = error.lower()

        # --- Pattern: "no module named X" / "cannot import X" ---
        m = re.search(r"no module named ['\"]?(\w[\w.]*)['\"]?", error_lower)
        if not m:
            m = re.search(r"cannot import name ['\"]?(\w+)['\"]?", error_lower)
        if m:
            missing = m.group(1).replace(".", "_")
            return self._spec_for_import_error(missing, task, error)

        # --- Pattern: "tool X not found" / "unknown tool" ---
        m = re.search(r"(?:tool|function|command|handler) ['\"]?(\w[\w_.-]*)['\"]? (?:not found|not available|unknown|missing|does not exist)", error_lower)
        if m:
            tool_ref = m.group(1).replace("-", "_").replace(".", "_").lower()
            return self._spec_for_missing_tool_ref(tool_ref, task, error)

        # --- Pattern: "KeyError: 'tool_name'" in RPC dispatch ---
        m = re.search(r"keyerror:\s*['\"](\w[\w.]*)['\"]", error_lower)
        if m and ("rpc" in error_lower or "endpoint" in error_lower or "dispatch" in error_lower):
            tool_ref = m.group(1).replace(".", "_").lower()
            return self._spec_for_missing_tool_ref(tool_ref, task, error)

        # --- Pattern: "FileNotFoundError" when the file would be a tool ---
        if "filenotfounderror" in error_lower:
            m = re.search(r"filenotfounderror.*?['\"](.+?\.py)['\"]", error_lower)
            if m:
                missing_file = Path(m.group(1)).stem
                return self._spec_for_missing_tool_ref(missing_file, task, error)

        # --- Pattern: explicit "missing capability" / "no handler for" ---
        m = re.search(r"(?:missing capability|no handler for|unsupported operation)[: ]+['\"]?(\w[\w_ ]*)", error_lower)
        if m:
            cap = m.group(1).strip().replace(" ", "_").lower()
            return self._spec_for_missing_tool_ref(cap, task, error)

        return None

    def _spec_for_import_error(self, missing_module: str, task: str, error: str) -> Dict:
        """Build a spec when the error is a missing Python module."""
        name = self._safe_name(f"synth_{missing_module}")
        return {
            "tool_name": name,
            "category": "analyzer",
            "description": f"Auto-created stub for missing module '{missing_module}' (triggered by import error during: {task[:120]})",
            "input_fields": ["input_data"],
            "logic_key": "passthrough",
            "params_signature": "input_data: str = ''",
            "triggered_by": error[:300],
        }

    def _spec_for_missing_tool_ref(self, tool_ref: str, task: str, error: str) -> Dict:
        """Build a spec when the error references a missing tool/function/handler."""
        name = self._safe_name(f"synth_{tool_ref}")

        # Try to infer category from the name
        category = "executor"
        logic_key = "passthrough"
        params = "input_data: str = ''"
        fields = ["input_data"]

        if any(kw in tool_ref for kw in ("analyz", "check", "inspect", "scan", "lint", "audit")):
            category = "analyzer"
            logic_key = "text_search"
            params = "text: str = '', pattern_str: str = '.*'"
            fields = ["text", "pattern_str"]
        elif any(kw in tool_ref for kw in ("generat", "create", "build", "scaffold", "write")):
            category = "generator"
            logic_key = "write_file"
            params = "target_path: str = '', content: str = ''"
            fields = ["target_path", "content"]
        elif any(kw in tool_ref for kw in ("read", "load", "fetch", "get", "list")):
            category = "analyzer"
            logic_key = "read_file"
            params = "source_path: str = ''"
            fields = ["source_path"]
        elif any(kw in tool_ref for kw in ("transform", "convert", "parse", "pipeline")):
            category = "data_pipeline"
            logic_key = "json_transform"
            params = "input_data: str = ''"
            fields = ["input_data"]
        elif any(kw in tool_ref for kw in ("run", "exec", "command", "shell", "process")):
            category = "executor"
            logic_key = "run_command"
            params = "command: str = ''"
            fields = ["command"]

        return {
            "tool_name": name,
            "category": category,
            "description": f"Auto-created tool for '{tool_ref}' (triggered during: {task[:120]})",
            "input_fields": fields,
            "logic_key": logic_key,
            "params_signature": params,
            "triggered_by": error[:300],
        }

    # ------------------------------------------------------------------
    # Synthesis — write the .py file and register
    # ------------------------------------------------------------------

    def synthesize(self, spec: Dict) -> Dict[str, Any]:
        """
        Generate a tool module from a spec dict:
            tool_name, category, description, input_fields,
            logic_key, params_signature, triggered_by

        Returns: {success, tool_name, file_path, error?}
        """
        name = spec.get("tool_name", "")
        if not SAFE_NAME_RE.match(name):
            return {"success": False, "tool_name": name, "error": f"Invalid tool name: {name!r}"}

        category = spec.get("category", "executor")
        template = TEMPLATES.get(category)
        if not template:
            return {"success": False, "tool_name": name, "error": f"Unknown category: {category}"}

        logic_key = spec.get("logic_key", "passthrough")
        logic_body_raw = LOGIC_SNIPPETS.get(logic_key, LOGIC_SNIPPETS["passthrough"])
        # Indent logic body to match the template's try: block (8 spaces)
        logic_lines = logic_body_raw.splitlines()
        logic_body = "\n".join("        " + line if line.strip() else "" for line in logic_lines)

        file_path = GENERATED_DIR / f"{name}.py"
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        try:
            code = template.format(
                tool_name=name,
                description=spec.get("description", "").replace('"', "'"),
                timestamp=timestamp,
                input_fields=json.dumps(spec.get("input_fields", ["input_data"])),
                params_signature=spec.get("params_signature", "input_data: str = ''"),
                logic_body=logic_body,
            )

            file_path.write_text(code, encoding="utf-8")
            logger.info(f"[ToolSynthesizer] Created tool module: {file_path}")

            # Register at runtime
            spec["file_path"] = str(file_path)
            self._record_tool(spec)
            self._register_runtime(name, file_path)

            return {"success": True, "tool_name": name, "file_path": str(file_path)}

        except Exception as e:
            logger.error(f"[ToolSynthesizer] Failed to synthesize {name}: {e}")
            return {"success": False, "tool_name": name, "error": str(e)}

    def _register_runtime(self, name: str, file_path: Path) -> None:
        """Import the generated module and register in the synthesized tools registry."""
        try:
            mod_path = f"src.tools.synthesized.generated.{name}"
            mod = importlib.import_module(mod_path)
            # Force reload in case it was cached from a previous attempt
            importlib.reload(mod)
            spec = getattr(mod, "TOOL_SPEC", {})

            from src.tools.synthesized import register_tool
            register_tool(name, mod_path, spec.get("func_name", "run"), spec)

            logger.info(f"[ToolSynthesizer] Runtime-registered: {name}")
        except Exception as e:
            logger.warning(f"[ToolSynthesizer] Import/register failed for {name}: {e}")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_name(raw: str) -> str:
        """Sanitise a string into a valid Python identifier."""
        cleaned = re.sub(r"[^a-z0-9_]", "_", raw.lower().strip())
        cleaned = re.sub(r"_+", "_", cleaned).strip("_")
        if not cleaned or not cleaned[0].isalpha():
            cleaned = "synth_" + cleaned
        return cleaned[:62]

    def get_tool_function(self, tool_name: str):
        """Return the callable for a synthesized tool, or None."""
        from src.tools.synthesized import get_tool
        entry = get_tool(tool_name)
        if not entry:
            return None
        try:
            mod = importlib.import_module(entry["module_path"])
            return getattr(mod, entry["func_name"], None)
        except Exception:
            return None
