"""
Week 2 Deployment: PR Review Agent Integration
Automatic code review and quality gate validation

Connected to Phase 42 & Phase 50 for autonomous PR management.
Triggered automatically when test generation reaches 2,000+ tests.
"""

import sys
import asyncio
import logging
from typing import Dict, List, Optional, Set
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
import json

# Import PR review agent
sys.path.insert(0, str(Path(__file__).parent.parent / "agent"))
from pr_review_agent import PullRequestReviewAgent, PullRequest, ReviewResult


logger = logging.getLogger(__name__)


@dataclass
class Phase42PRForReview:
    """PR generated by Phase 42 (or test PR from Week 1)"""
    pr_id: str
    pr_number: int
    files_changed: List[str]
    test_pr: bool = False  # Is this a test PR from Week 1?
    parent_pr_id: Optional[str] = None  # Link to original if test PR
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class ReviewCascadeResult:
    """Result of PR review cascade"""
    pr_id: str
    review_result: ReviewResult
    approval_decision: str  # APPROVED, NEEDS_CHANGES, BLOCKED
    auto_merge_enabled: bool
    cascade_to_phase: Optional[str] = None  # Phase 41, 42, 51, etc.
    quality_score: float = 0.0


class Week2PRReviewIntegration:
    """
    Week 2: Integrate PR Review Agent with Phase 42 PR pipeline.
    
    Automatically reviews all Phase 42 refactoring PRs and test PRs
    with 20+ quality patterns.
    """
    
    def __init__(self, config: Optional[Dict] = None):
        """Initialize PR review integration"""
        self.review_agent = PullRequestReviewAgent()
        self.config = config or self._default_config()
        self.reviewed_prs_count = 0
        self.approved_prs = []
        self.blocked_prs = []
        self.logger = logging.getLogger(f"{__name__}.Week2Review")
    
    def _default_config(self) -> Dict:
        """Default configuration for Week 2 PR review"""
        return {
            "enabled": True,
            "trigger": "test_pr_generation_complete",  # After Week 1 tests
            "auto_approve_threshold": 0.85,  # 85%+ score = auto-approve
            "auto_merge_threshold": 0.90,    # 90%+ score = auto-merge
            "quality_gates": {
                "min_coverage": 0.70,
                "max_complexity": 10.0,
                "require_tests": True,
                "allow_critical_issues": False,
            },
            "parallel_reviews": 10,  # Review up to 10 PRs in parallel
            "batch_size": 45,  # All Phase 42 PRs per night
            "create_comments": True,  # Add review comments
            "link_test_prs": True,  # Link to associated test PR
        }
    
    async def review_pr_batch(
        self,
        pr_metadata_list: List[Phase42PRForReview]
    ) -> List[ReviewCascadeResult]:
        """
        Review a batch of Phase 42 PRs (up to 45/night).
        
        Args:
            pr_metadata_list: List of PRs to review
            
        Returns:
            List of review cascade results
        """
        self.logger.info(f"Reviewing {len(pr_metadata_list)} PRs...")
        
        results = []
        
        # Process in parallel batches
        for i in range(0, len(pr_metadata_list), self.config["parallel_reviews"]):
            batch = pr_metadata_list[i:i + self.config["parallel_reviews"]]
            
            batch_results = await asyncio.gather(
                *[self._review_single_pr(pr) for pr in batch]
            )
            results.extend(batch_results)
        
        return results
    
    async def _review_single_pr(self, pr: Phase42PRForReview) -> ReviewCascadeResult:
        """Review a single PR using the review agent"""
        try:
            start_time = datetime.utcnow()
            
            # Create PullRequest object for review agent
            pull_request = PullRequest(
                pr_id=pr.pr_id,
                title=f"{'Test PR for ' if pr.test_pr else ''}{pr.pr_id}",
                files=[],  # In production, would read actual files
                author="phase42_refactor_engine",
                created_at=pr.timestamp,
            )
            
            # Review using PR review agent
            review_result = self.review_agent.review_pr(pull_request)
            
            # Determine approval decision
            approval_decision = self._determine_approval(review_result)
            
            # Calculate quality score (0-100)
            quality_score = self._calculate_quality_score(review_result)
            
            # Decide cascading action
            cascade_target = self._determine_cascade(approval_decision, quality_score)
            
            result = ReviewCascadeResult(
                pr_id=pr.pr_id,
                review_result=review_result,
                approval_decision=approval_decision,
                auto_merge_enabled=(quality_score >= self.config["auto_merge_threshold"]),
                cascade_to_phase=cascade_target,
                quality_score=quality_score,
            )
            
            # Track results
            self.reviewed_prs_count += 1
            if approval_decision == "APPROVED":
                self.approved_prs.append(pr.pr_id)
            elif approval_decision == "BLOCKED":
                self.blocked_prs.append(pr.pr_id)
            
            time_taken = (datetime.utcnow() - start_time).total_seconds()
            self.logger.info(
                f"✓ Reviewed PR {pr.pr_id}: "
                f"{approval_decision} ({quality_score:.0%}), "
                f"{time_taken:.2f}s"
            )
            
            return result
            
        except Exception as e:
            self.logger.error(f"Error reviewing PR {pr.pr_id}: {e}")
            return ReviewCascadeResult(
                pr_id=pr.pr_id,
                review_result=None,
                approval_decision="BLOCKED",
                auto_merge_enabled=False,
                quality_score=0.0,
            )
    
    def _determine_approval(self, review_result: ReviewResult) -> str:
        """Determine approval status based on review result"""
        if review_result is None:
            return "BLOCKED"
        
        if review_result.result == "APPROVED":
            return "APPROVED"
        elif review_result.result == "APPROVED_WITH_MINOR_ISSUES":
            return "APPROVED"
        elif review_result.result == "NEEDS_CHANGES":
            return "NEEDS_CHANGES"
        else:  # BLOCKED
            return "BLOCKED"
    
    def _calculate_quality_score(self, review_result: ReviewResult) -> float:
        """Calculate 0-1 quality score from review result"""
        if review_result is None:
            return 0.0
        
        # Normalize review result score to 0-1
        if hasattr(review_result, 'approval_score'):
            return review_result.approval_score
        
        # Default: 0.85 for APPROVED + MINOR, 0.5 for NEEDS_CHANGES, 0.0 for BLOCKED
        if review_result.result == "APPROVED":
            return 0.95
        elif review_result.result == "APPROVED_WITH_MINOR_ISSUES":
            return 0.85
        elif review_result.result == "NEEDS_CHANGES":
            return 0.5
        else:
            return 0.0
    
    def _determine_cascade(self, approval: str, quality_score: float) -> Optional[str]:
        """Determine which phase to cascade approval to"""
        
        # APPROVED with high quality → cascade to Phase 41 (coordination)
        if approval == "APPROVED" and quality_score >= 0.90:
            return "phase41"
        
        # APPROVED with medium quality → cascade to Phase 42 (apply refactor)
        if approval == "APPROVED" and quality_score >= 0.80:
            return "phase42"
        
        # APPROVED but lower quality → manual review queue
        if approval == "APPROVED":
            return "manual_queue"
        
        # NEEDS_CHANGES → send to developer queue
        if approval == "NEEDS_CHANGES":
            return "developer_queue"
        
        # BLOCKED → escalation queue
        return "escalation"
    
    def get_review_metrics(self) -> Dict:
        """Get review session metrics"""
        total = self.reviewed_prs_count
        return {
            "timestamp": datetime.utcnow().isoformat(),
            "prs_reviewed": total,
            "prs_approved": len(self.approved_prs),
            "prs_blocked": len(self.blocked_prs),
            "approval_rate": len(self.approved_prs) / max(total, 1),
            "auto_merge_rate": (
                len([p for p in self.approved_prs if len(p) > 0]) / max(total, 1)
                if self.approved_prs else 0.0
            ),
        }
    
    def generate_review_report(self) -> str:
        """Generate human-readable review report"""
        metrics = self.get_review_metrics()
        
        return f"""
╔═══════════════════════════════════════════════════════════════════════════╗
║                   WEEK 2: PR REVIEW AGENT DEPLOYMENT                     ║
║                  Autonomous Quality Gate Validation                       ║
╚═══════════════════════════════════════════════════════════════════════════╝

📊 REVIEW METRICS:
  • Total PRs Reviewed: {metrics['prs_reviewed']}
  • PRs Approved: {metrics['prs_approved']}
  • PRs Blocked: {metrics['prs_blocked']}
  • Approval Rate: {metrics['approval_rate']:.0%}
  • Auto-Merge Rate: {metrics['auto_merge_rate']:.0%}

🎯 QUALITY GATES ACTIVE:
  • Min Coverage: 70%
  • Max Complexity: 10.0
  • Require Tests: YES
  • Allow Critical Issues: NO
  • Auto-Approve Threshold: 85%
  • Auto-Merge Threshold: 90%

⚡ CAPABILITIES:
  • 20+ Code Quality Patterns Detected
  • Security Issue Detection (SQL injection, auth, credentials)
  • Test Coverage Analysis
  • Complexity Scoring
  • Parallel Review: 10 PRs simultaneously
  • Batch Review: Up to 45 PRs/night

🔄 CASCADE ROUTING:
  • Quality 90%+: → Phase 41 (Coordination)
  • Quality 80%+: → Phase 42 (Apply Refactor)
  • Quality 70-80%: → Manual Review Queue
  • Quality <70%: → Developer/Escalation Queue

✨ STATUS: AUTONOMOUS PR REVIEW ACTIVE

Expected Week 2 Impact:
  • Test PRs: Auto-reviewed within seconds
  • Refactor PRs: Quality validation enabled
  • Merge Rate: 85%+ auto-approval target
  • Coverage: 28% → 50%+ by end of week
"""


async def example_week2_review():
    """Example: Week 2 PR review session"""
    
    # Simulate Phase 42 + Week 1 test PRs
    sample_prs = [
        Phase42PRForReview(
            pr_id="test_pr_001",
            pr_number=100,
            files_changed=["src/phase1_authentication.py", "tests/test_auth.py"],
            test_pr=True,
            parent_pr_id="phase42_refactor_001"
        ),
        Phase42PRForReview(
            pr_id="phase42_refactor_002",
            pr_number=101,
            files_changed=["src/phase2_api_gateway.py"],
            test_pr=False,
        ),
        Phase42PRForReview(
            pr_id="test_pr_002",
            pr_number=102,
            files_changed=["src/phase3_database.py", "tests/test_db.py"],
            test_pr=True,
            parent_pr_id="phase42_refactor_002"
        ),
    ]
    
    print("🚀 WEEK 2 PR REVIEW INTEGRATION - EXAMPLE\n")
    
    integration = Week2PRReviewIntegration()
    results = await integration.review_pr_batch(sample_prs)
    
    print(f"Processed {len(results)} PRs\n")
    
    for result in results:
        status = "✅" if result.approval_decision == "APPROVED" else "❌"
        print(f"{status} {result.pr_id}: {result.approval_decision} ({result.quality_score:.0%})")
        if result.cascade_to_phase:
            print(f"   → Cascade: {result.cascade_to_phase}")
    
    print(integration.generate_review_report())


if __name__ == "__main__":
    asyncio.run(example_week2_review())
